name: Mypy (Type check)
on: [push, pull_request]
env:
  PYTHON_VERSION: "3.10"

jobs:
  mypy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry 🎸
        uses: ThePalaceProject/circulation/.github/actions/poetry@main
        with:
          version: "1.7.1"

      - name: Install OS Packages 🧰
        run: |
          sudo apt-get update

      - name: Install Python Packages 📦
        run: poetry install --without ci

      - name: Run MyPy 🪄
        run: poetry run mypy
